/var/spool/slurm/slurmd/job5535420/slurm_script: line 9: cd: /gpfs/home4/scur0755/5LSM0-Final-Assignment/: No such file or directory
mkdir: cannot create directory 'wandb/5535420': No such file or directory
wandb: WARNING Path wandb/5535420/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path wandb/5535420/wandb/ wasn't writable, using system temp directory.
wandb: WARNING Path wandb/5535420/wandb/ wasn't writable, using system temp directory
wandb: Currently logged in as: ldeben20 (luciano-deben). Use `wandb login --relogin` to force relogin
Collecting keras
  Using cached keras-3.0.5-py3-none-any.whl.metadata (4.8 kB)
Collecting absl-py (from keras)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from keras) (1.24.1)
Collecting rich (from keras)
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras)
  Using cached namex-0.0.7-py3-none-any.whl.metadata (246 bytes)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from keras) (3.10.0)
Collecting dm-tree (from keras)
  Using cached dm_tree-0.1.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
Collecting ml-dtypes (from keras)
  Using cached ml_dtypes-0.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->keras)
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached keras-3.0.5-py3-none-any.whl (1.0 MB)
Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
Using cached dm_tree-0.1.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (152 kB)
Using cached ml_dtypes-0.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
Using cached namex-0.0.7-py3-none-any.whl (5.8 kB)
Using cached rich-13.7.1-py3-none-any.whl (240 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, dm-tree, pygments, ml-dtypes, mdurl, absl-py, markdown-it-py, rich, keras
ERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.10/dist-packages/namex'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python3 -m pip install --upgrade pip
Traceback (most recent call last):
  File "/gpfs/home1/scur0755/5LSM0-Final-Assignment/train.py", line 11, in <module>
    import keras
ModuleNotFoundError: No module named 'keras'
[2024-03-14 10:33:55,242] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 555881) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-14_10:33:55
  host      : gcn42.local.snellius.surf.nl
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 555881)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: gcn42: task 0: Exited with exit code 1
srun: Terminating StepId=5535420.0

JOB STATISTICS
==============
Job ID: 5535420
Cluster: snellius
User/Group: scur0755/scur0755
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 18
CPU Utilized: 00:00:15
CPU Efficiency: 1.89% of 00:13:12 core-walltime
Job Wall-clock time: 00:00:44
Memory Utilized: 2.64 MB
Memory Efficiency: 0.00% of 120.00 GB
